server:
  port: 7001
spring:
  application:
    name: plm-fema-plugin
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 724256489
    url: jdbc:sqlserver://172.21.6.232:1433;DatabaseName=Tech_PLM
  redis:
    host: 172.21.0.36
    port: 6379
    password: 123456
    jedis:
       pool:
         max-active: -1 #连接池最大连接数,负值表示没有限制
         max-idle: 10   #连接池的最大空闲连接
         min-idle: 0    #连接池的最小空闲连接
         max-wait: -1ms  #连接池最大阻塞等待时间
    timeout: 5000ms
    database: 0
  #文件上传设置
  servlet:
    multipart:
      max-request-size: 100GB   #单次请求上传文件大小总和最大值
      max-file-size: 10GB   #单个文件大小最大值
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath\:/META-INF/resources/,classpath\:/resources/,classpath\:/static/
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.viwo.fema.entity
  #configuration:
    #map-underscore-to-camel-case: true
pagehelper:
  helperDialect: sqlserver  #标识是哪一种数据库
  reasonable: true  #启用合理化，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页
  supportMethodsArguments: true #支持通过 Mapper 接口参数来传递分页参数，默认值false，分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页
  params: count=countSql  #为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值
  page-size-zero: true  #如果 pageSize=0 就会查询出全部的结果（相当于没有执行分页查询）
#文件上传路径设置
fileupload:
  template-path: D:\PLMFEMA管理插件\uploadfile\templatefile\  #Fmea模板文件路径
  template-xdpath: /templatefile/ #Fmea模板文件相对头路径
  fmea-path: D:\PLMFEMA管理插件\uploadfile\fmeafile\  #FMEA文件路径
  fmea-xdpath: /fmeafile/  #FMEA文件路径

logging:
  level:
     com.viwo.fema.dao: debug   #打印sql


